-- ============================================================
-- FREELANCE HUB SA
-- DEMO MARKETPLACE ENGINE
-- FILE: 01_lookup_tables.sql
--
-- Purpose:
-- Creates reusable lookup tables used by the demo marketplace
-- generators.
--
-- This script does not delete or modify existing marketplace
-- users, jobs, clients or applications.
-- ============================================================


-- ============================================================
-- 1. JOB TEMPLATE LIBRARY
-- ============================================================

create table if not exists public.demo_job_templates (
  id bigint generated by default as identity primary key,

  category text not null,
  title text not null,
  description_template text not null,

  min_budget numeric(12, 2) not null default 500,
  max_budget numeric(12, 2) not null default 5000,

  min_duration_days integer not null default 2,
  max_duration_days integer not null default 14,

  experience_level text not null default 'Intermediate',

  skills text[] not null default '{}',

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint demo_job_templates_budget_check
    check (
      min_budget >= 0
      and max_budget >= min_budget
    ),

  constraint demo_job_templates_duration_check
    check (
      min_duration_days > 0
      and max_duration_days >= min_duration_days
    ),

  constraint demo_job_templates_experience_check
    check (
      experience_level in (
        'Entry Level',
        'Intermediate',
        'Expert'
      )
    )
);


-- Prevent duplicate job templates.

create unique index if not exists
demo_job_templates_unique_title_category_idx
on public.demo_job_templates (
  lower(category),
  lower(title)
);


-- ============================================================
-- 2. LOCATION LIBRARY
-- ============================================================

create table if not exists public.demo_marketplace_locations (
  id bigint generated by default as identity primary key,

  city text not null,
  province text,
  country text not null default 'South Africa',

  work_type text not null default 'Remote',

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  constraint demo_marketplace_locations_work_type_check
    check (
      work_type in (
        'Remote',
        'On-site',
        'Hybrid'
      )
    )
);


create unique index if not exists
demo_marketplace_locations_unique_idx
on public.demo_marketplace_locations (
  lower(city),
  lower(coalesce(province, '')),
  lower(work_type)
);


-- ============================================================
-- 3. FREELANCER PROFESSION LIBRARY
-- ============================================================

create table if not exists public.demo_freelancer_templates (
  id bigint generated by default as identity primary key,

  category text not null,
  headline text not null,

  bio_template text not null,

  skills text[] not null default '{}',

  minimum_hourly_rate numeric(10, 2) not null default 150,
  maximum_hourly_rate numeric(10, 2) not null default 500,

  minimum_experience_years integer not null default 1,
  maximum_experience_years integer not null default 8,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint demo_freelancer_templates_rate_check
    check (
      minimum_hourly_rate >= 0
      and maximum_hourly_rate >= minimum_hourly_rate
    ),

  constraint demo_freelancer_templates_experience_check
    check (
      minimum_experience_years >= 0
      and maximum_experience_years >= minimum_experience_years
    )
);


create unique index if not exists
demo_freelancer_templates_unique_idx
on public.demo_freelancer_templates (
  lower(category),
  lower(headline)
);


-- ============================================================
-- 4. SOUTH AFRICAN NAME LIBRARY
-- ============================================================

create table if not exists public.demo_person_names (
  id bigint generated by default as identity primary key,

  first_name text not null,
  last_name text not null,

  is_active boolean not null default true,

  created_at timestamptz not null default now()
);


create unique index if not exists
demo_person_names_unique_idx
on public.demo_person_names (
  lower(first_name),
  lower(last_name)
);


-- ============================================================
-- 5. COMPANY TEMPLATE LIBRARY
-- ============================================================

create table if not exists public.demo_company_templates (
  id bigint generated by default as identity primary key,

  display_name text not null,
  industry text not null,

  city text,
  province text,
  country text not null default 'South Africa',

  company_description text,

  verified boolean not null default true,
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create unique index if not exists
demo_company_templates_unique_name_idx
on public.demo_company_templates (
  lower(display_name)
);


-- ============================================================
-- 6. APPLICATION PROPOSAL LIBRARY
-- ============================================================

create table if not exists public.demo_proposal_templates (
  id bigint generated by default as identity primary key,

  category text not null,

  proposal_template text not null,

  minimum_completion_days integer not null default 2,
  maximum_completion_days integer not null default 14,

  bid_percentage_min numeric(5, 2) not null default 75,
  bid_percentage_max numeric(5, 2) not null default 110,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  constraint demo_proposal_templates_days_check
    check (
      minimum_completion_days > 0
      and maximum_completion_days >= minimum_completion_days
    ),

  constraint demo_proposal_templates_bid_check
    check (
      bid_percentage_min > 0
      and bid_percentage_max >= bid_percentage_min
    )
);


-- ============================================================
-- 7. MARKETPLACE ENGINE SETTINGS
-- ============================================================

create table if not exists public.demo_marketplace_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  description text,

  updated_at timestamptz not null default now()
);


-- Default settings used by future generator functions.

insert into public.demo_marketplace_settings (
  setting_key,
  setting_value,
  description
)
values
  (
    'job_expiry_days',
    '14'::jsonb,
    'Default number of days before a demo job expires.'
  ),
  (
    'featured_job_percentage',
    '15'::jsonb,
    'Approximate percentage of generated demo jobs marked as featured.'
  ),
  (
    'verified_freelancer_percentage',
    '85'::jsonb,
    'Approximate percentage of generated demo freelancers marked as verified.'
  ),
  (
    'top_rated_freelancer_percentage',
    '20'::jsonb,
    'Approximate percentage of demo freelancers marked as top rated.'
  ),
  (
    'maximum_applications_per_job',
    '8'::jsonb,
    'Maximum number of generated demo applications per job.'
  ),
  (
    'minimum_applications_per_job',
    '1'::jsonb,
    'Minimum preferred number of generated demo applications per job.'
  )
on conflict (setting_key)
do update set
  description = excluded.description,
  updated_at = now();


-- ============================================================
-- 8. UPDATED_AT FUNCTION
-- ============================================================

create or replace function public.set_demo_marketplace_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================
-- 9. UPDATED_AT TRIGGERS
-- ============================================================

drop trigger if exists
set_demo_job_templates_updated_at
on public.demo_job_templates;

create trigger set_demo_job_templates_updated_at
before update on public.demo_job_templates
for each row
execute function public.set_demo_marketplace_updated_at();


drop trigger if exists
set_demo_freelancer_templates_updated_at
on public.demo_freelancer_templates;

create trigger set_demo_freelancer_templates_updated_at
before update on public.demo_freelancer_templates
for each row
execute function public.set_demo_marketplace_updated_at();


drop trigger if exists
set_demo_company_templates_updated_at
on public.demo_company_templates;

create trigger set_demo_company_templates_updated_at
before update on public.demo_company_templates
for each row
execute function public.set_demo_marketplace_updated_at();


drop trigger if exists
set_demo_marketplace_settings_updated_at
on public.demo_marketplace_settings;

create trigger set_demo_marketplace_settings_updated_at
before update on public.demo_marketplace_settings
for each row
execute function public.set_demo_marketplace_updated_at();


-- ============================================================
-- 10. BASIC TABLE PERMISSIONS
-- ============================================================
--
-- These tables are intended to be managed by administrators
-- and PostgreSQL functions.
--
-- The public website does not need direct access to them.
-- ============================================================

alter table public.demo_job_templates enable row level security;
alter table public.demo_marketplace_locations enable row level security;
alter table public.demo_freelancer_templates enable row level security;
alter table public.demo_person_names enable row level security;
alter table public.demo_company_templates enable row level security;
alter table public.demo_proposal_templates enable row level security;
alter table public.demo_marketplace_settings enable row level security;


-- ============================================================
-- 11. ADMIN READ POLICIES
-- ============================================================
--
-- These policies assume profiles contains:
--   id
--   is_admin
--
-- They allow authenticated administrators to view the lookup
-- data through Supabase.
-- ============================================================

drop policy if exists
"Admins can view demo job templates"
on public.demo_job_templates;

create policy
"Admins can view demo job templates"
on public.demo_job_templates
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo locations"
on public.demo_marketplace_locations;

create policy
"Admins can view demo locations"
on public.demo_marketplace_locations
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo freelancer templates"
on public.demo_freelancer_templates;

create policy
"Admins can view demo freelancer templates"
on public.demo_freelancer_templates
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo person names"
on public.demo_person_names;

create policy
"Admins can view demo person names"
on public.demo_person_names
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo company templates"
on public.demo_company_templates;

create policy
"Admins can view demo company templates"
on public.demo_company_templates
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo proposal templates"
on public.demo_proposal_templates;

create policy
"Admins can view demo proposal templates"
on public.demo_proposal_templates
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


drop policy if exists
"Admins can view demo marketplace settings"
on public.demo_marketplace_settings;

create policy
"Admins can view demo marketplace settings"
on public.demo_marketplace_settings
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);


-- ============================================================
-- 12. VERIFICATION
-- ============================================================

select
  table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'demo_job_templates',
    'demo_marketplace_locations',
    'demo_freelancer_templates',
    'demo_person_names',
    'demo_company_templates',
    'demo_proposal_templates',
    'demo_marketplace_settings'
  )
order by table_name;